import { SectionHeader } from '../components/SectionHeader';
import { Text } from '../components/Text';
import Head from 'next/head';
import React from 'react';
import css from './our-story.module.scss';

export default function OurStory({}) {
  return (
    <>
      <Head>
        <title>Molly &amp; John&apos;s Story</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SectionHeader title="Our Story" subtitle="The story of Jolly" />

      <div className={css.storyWrapper}>
        <Text variant="body2" tag="p">
          When you think of romantic locations around the globe, what comes to
          mind? The Eiffel Tower sparkling at night? The California coastline
          during sunset? The chalk white buildings of Santorini, Greece? How
          about… a storage unit along Buford Highway in Chamblee, Georgia?
        </Text>
        <Text variant="body2" tag="p">
          That&apos;s right. The story of Molly and John began in a 5&apos; x
          10&apos; storage unit. In 2017, Molly made the tough decision to pack
          up her things in New York City and move down to Atlanta to pursue a
          career in User Experience Design. Molly&apos;s best friend, Laura,
          offered up her at-the-time fiancé now husband, Brian, and a few of his
          friends to assist Molly in unloading the U-Haul upon her arrival in
          ATL.
        </Text>
        <Text variant="body2" tag="p">
          We could go on, but we don&apos;t want to bore you with a novel.
          Instead, here are a few photos that tell the story of us. Please
          enjoy.
        </Text>
        <Text variant="body2" tag="p">
          &lt;3 jolly
        </Text>
      </div>
    </>
  );
}
