import Head from 'next/head';
import React from 'react';
import { Calendar, WeddingEvent } from '../components/Calendar';
import { SectionHeader } from '../components/SectionHeader';
import css from './weekend.module.scss';

const events: WeddingEvent[] = [
  {
    id: 'golf',
    name: 'Golf Tournament',
    shortName: 'Golf',
    location: 'Hiwan Golf Club',
    description:
      "Fun round of golf at Hiwan Golf Club. Entry is $100 / player. Closest to the pin, longest drive, and low net rewards will be given out! Don't forget to RSVP for this separately so can book the appropriate number of tee times.",
    startTime: new Date(2023, 7, 25, 8),
    endTime: new Date(2023, 7, 25, 13),
    day: 'Friday',
  },
  {
    id: 'welcome-party',
    name: 'Welcome Party',
    shortName: 'Welcome Party',
    location: 'Revival Brewing',
    description:
      'Join us for drinks and jolly good times in downtown Evergreen as we kick off the weekend!',
    startTime: new Date(2023, 7, 25, 18),
    endTime: new Date(2023, 7, 25, 21),
    day: 'Friday',
  },
  {
    id: 'ceremony',
    name: 'Ceremony and Reception',
    shortName: 'Ceremony & Reception',
    location: 'Hiwan Golf Club',
    startTime: new Date(2023, 7, 26, 16),
    endTime: new Date(2023, 7, 26, 22),
    day: 'Saturday',
  },
  {
    id: 'afterparty',
    name: 'After Party',
    shortName: 'After Party',
    location: 'Little Bear Saloon',
    startTime: new Date(2023, 7, 26, 22, 30),
    endTime: new Date(2023, 7, 26, 24),
    day: 'Saturday',
  },
];

export default function Home({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly Wedding Weekend</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SectionHeader title="Wedding Weekend" />

      <div className={css['calendar-container']}>
        <Calendar events={events} />
      </div>
    </>
  );
}
