import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { McpAgent } from 'agents/mcp';
import { z } from 'zod';
import { checkBearer } from './auth';
import { CoachClient, CoachApiError } from './coachClient';

// Env (MCP_OBJECT, COACH_SITE_BASE_URL, COACH_API_TOKEN) is the ambient global
// type generated by `wrangler types` from wrangler.jsonc + .dev.vars — run
// `bun run cf-typegen` after cloning or after changing either file.
// COACH_API_TOKEN doubles as this worker's own inbound auth (see fetch below).

// Mirrors src/lib/coach/types.ts in johnverrone/. Duplicated because this is a
// separate deployable with no shared package; keep in sync by hand.
const MODALITIES = ['lift', 'run', 'bike', 'hiit', 'hike', 'walk', 'mobility', 'rest'] as const;
const WORKOUT_STATUSES = ['done', 'skipped', 'modified'] as const;
const WORKOUT_VARIANTS = ['full', 'bare_min'] as const;
const CHECK_IN_TYPES = ['daily', 'weekly'] as const;

const text = (value: unknown) => ({
	content: [{ type: 'text' as const, text: JSON.stringify(value, null, 2) }]
});

const errorText = (message: string) => ({
	content: [{ type: 'text' as const, text: message }],
	isError: true
});

export class CoachMCP extends McpAgent<Env> {
	server = new McpServer({ name: 'johnverrone-coach', version: '1.0.0' });

	private get client() {
		return new CoachClient({ baseUrl: this.env.COACH_SITE_BASE_URL, token: this.env.COACH_API_TOKEN });
	}

	async init() {
		this.server.registerTool(
			'get_today',
			{
				description:
					"Today's planned session, logged workouts, habit toggles, streaks, latest coach check-in, and this week's adherence.",
				inputSchema: { date: z.string().optional().describe('yyyy-mm-dd, defaults to today') }
			},
			async ({ date }) => this.run(() => this.client.getToday(date))
		);

		this.server.registerTool(
			'get_summary',
			{
				description:
					'Rolling summary for a weekly review: adherence, streaks, training volume by modality, recent logs, latest body metrics, recent check-ins.',
				inputSchema: { days: z.number().int().min(1).max(90).optional().describe('default 7') }
			},
			async ({ days }) => this.run(() => this.client.getSummary(days))
		);

		this.server.registerTool(
			'get_plan',
			{ description: 'The full weekly plan template (all seven days).', inputSchema: {} },
			async () => this.run(() => this.client.getPlan())
		);

		this.server.registerTool(
			'update_plan_session',
			{
				description:
					'Create, patch, or delete a session in the weekly plan template. Omit id to create; pass id to patch; pass id + delete:true to remove.',
				inputSchema: {
					id: z.number().int().optional(),
					delete: z.boolean().optional(),
					name: z.string().optional(),
					modality: z.enum(MODALITIES).optional(),
					day_of_week: z.number().int().min(0).max(6).optional().describe('0=Sunday..6=Saturday'),
					sort_order: z.number().int().optional(),
					duration_min: z.number().int().nullable().optional(),
					prescription: z.string().nullable().optional(),
					bare_min: z.string().nullable().optional(),
					bare_min_duration_min: z.number().int().nullable().optional(),
					active: z.boolean().optional()
				}
			},
			async (input) => this.run(() => this.client.updatePlanSession(input))
		);

		this.server.registerTool(
			'log_workout',
			{
				description: 'Log a completed, skipped, or modified workout.',
				inputSchema: {
					date: z.string().optional().describe('yyyy-mm-dd, defaults to today'),
					status: z.enum(WORKOUT_STATUSES),
					modality: z.enum(MODALITIES),
					plan_session_id: z.number().int().optional(),
					duration_min: z.number().int().optional(),
					rpe: z.number().int().min(1).max(10).optional(),
					notes: z.string().optional(),
					variant: z.enum(WORKOUT_VARIANTS).optional()
				}
			},
			async (input) => this.run(() => this.client.logWorkout(input))
		);

		this.server.registerTool(
			'log_habit',
			{
				description: "Patch today's (or a given date's) habit toggles: no added sugar, no alcohol, mobility.",
				inputSchema: {
					date: z.string().optional().describe('yyyy-mm-dd, defaults to today'),
					no_added_sugar: z.boolean().optional(),
					no_alcohol: z.boolean().optional(),
					mobility_done: z.boolean().optional(),
					notes: z.string().optional()
				}
			},
			async (input) => this.run(() => this.client.logHabit(input))
		);

		this.server.registerTool(
			'post_checkin',
			{
				description:
					'Post a coach check-in message (markdown) — shows up on the Today page. Use for daily nudges or the weekly review.',
				inputSchema: {
					type: z.enum(CHECK_IN_TYPES),
					content: z.string(),
					date: z.string().optional().describe('yyyy-mm-dd, defaults to today')
				}
			},
			async (input) => this.run(() => this.client.postCheckin(input))
		);
	}

	/** Run a coach API call, turning failures into MCP tool errors instead of throwing. */
	private async run(fn: () => Promise<unknown>) {
		try {
			return text(await fn());
		} catch (e) {
			return errorText(e instanceof CoachApiError ? e.message : `Unexpected error: ${e}`);
		}
	}
}

export default {
	async fetch(request: Request, env: Env, ctx: ExecutionContext) {
		const url = new URL(request.url);
		if (url.pathname !== '/mcp') return new Response('Not found', { status: 404 });

		if (!(await checkBearer(request, env.COACH_API_TOKEN))) {
			return new Response('Unauthorized', { status: 401 });
		}
		return CoachMCP.serve('/mcp').fetch(request, env, ctx);
	}
};
