import Head from 'next/head';
import React from 'react';
import { Text } from 'components/Text';
import css from '../styles/Home.module.css';

export default function Home({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly 2023</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={css.splashImage} />

      <div className={css.headingWrapper}>
        <Text variant="heading1">The Wedding</Text>
        <Text variant="body2">July 22, 2023 &middot; Buena Vista, CO</Text>
      </div>
    </>
  );
}
