import { SectionHeader } from 'components/SectionHeader';
import Head from 'next/head';
import React from 'react';

export default function OurStory({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly&apos;s Story</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SectionHeader title="Our Story" subtitle="The story of Jolly" />
    </>
  );
}
