import Head from 'next/head';
import React from 'react';

export default function Home({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly&apos;s Registry</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
}
