import Head from 'next/head';
import React from 'react';
import { SectionHeader } from 'components/SectionHeader';
import css from '../styles/rsvp.module.css';
import { TextInput } from 'components/TextInput';
import { Button } from 'components/Button';

export default function Home({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly RSVP</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SectionHeader title="RSVP" subtitle="so... you comin?" />

      <form
        className={css.rsvpForm}
        onSubmit={(e) => {
          e.preventDefault();
          alert('thank you');
        }}
      >
        <div className={css.formItem}>
          <label htmlFor="name">Name</label>
          <TextInput
            type="text"
            id="name"
            autoComplete="name"
            placeholder="Benjamin Evalent"
          />
        </div>
        <div className={css.formItem}>
          <label htmlFor="email">Email</label>
          <TextInput
            type="email"
            id="email"
            autoComplete="email"
            placeholder="benevalent@gmail.com"
          />
        </div>
        <div className={css.formItem}>
          <span>Attendance</span>
          <div>
            <input type="radio" name="attendance" id="attendance-yes" />
            <label htmlFor="attendance">Yes</label>
            <input type="radio" name="attendance" id="attendance-no" />
            <label htmlFor="attendance">No</label>
          </div>
        </div>
        <Button type="submit" variant="primary">
          Submit
        </Button>
      </form>
    </>
  );
}
