import Head from 'next/head';
import React from 'react';
import { SectionHeader } from 'components/SectionHeader';

export default function Home({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly RSVP</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SectionHeader title="RSVP" subtitle="so... you comin?" />

      <form>
        <div>
          <label htmlFor="name">Name</label>
          <input type="text" id="name" />
        </div>
        <div>
          <label htmlFor="email">Email</label>
          <input type="email" id="email" />
        </div>
        <div>
          <span>Attendance</span>
          <input type="radio" name="attendance" id="attendance-yes" />
          <label htmlFor="attendance">Yes</label>
          <input type="radio" name="attendance" id="attendance-no" />
          <label htmlFor="attendance">No</label>
        </div>
      </form>
    </>
  );
}
