import Head from 'next/head';
import React from 'react';
import { Text } from 'components/Text';
import css from '../styles/Weekend.module.css';
import { SectionHeader } from 'components/SectionHeader';

export default function Home({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly Wedding Weekend</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <SectionHeader
        title="Wedding Weekend"
        subtitle="This is what's going down"
      />
    </>
  );
}
