import Head from 'next/head';
import React from 'react';
import { Text } from 'components/Text';
import css from '../styles/Weekend.module.css';

export default function Home({}) {
  return (
    <>
      <Head>
        <title>John &amp; Molly Wedding Weekend</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={css.headingWrapper}>
        <Text variant="heading1">Wedding Weekend</Text>
        <Text variant="body2">this is what&apos;s going down</Text>
      </div>
    </>
  );
}
