import OAuthProvider from '@cloudflare/workers-oauth-provider';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { McpAgent } from 'agents/mcp';
import { z } from 'zod';
import { GitHubHandler } from './github-handler';
import type { Props } from './github-oauth';
import { CommandCenterClient, CommandCenterApiError } from './apiClient';

// Env (MCP_OBJECT, OAUTH_KV, COACH_SITE_BASE_URL, COACH_API_TOKEN,
// GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, COOKIE_ENCRYPTION_KEY) is the
// ambient global type generated by `wrangler types` from wrangler.jsonc +
// .dev.vars — run `bun run cf-typegen` after cloning or changing either file.
//
// Inbound auth (who may open an MCP session) is GitHub OAuth via
// OAuthProvider below, gated to a single username in github-handler.ts.
// COACH_API_TOKEN is unrelated to that — it's this worker's own credential
// for its *outbound* calls to johnverrone.com's /api/* contracts.
//
// Tools are namespaced by prefix (coach_*, guitar_*, coffee_*) rather than split across
// servers — MCP has no native tool-grouping concept, and splitting would mean
// duplicating this entire OAuth/KV/DO setup per domain. Revisit if the tool
// count crosses ~15-20 or a domain stops fitting "personal command center."

// Mirrors src/lib/coach/types.ts in johnverrone/. Duplicated because this is a
// separate deployable with no shared package; keep in sync by hand.
const MODALITIES = ['lift', 'run', 'bike', 'hiit', 'hike', 'walk', 'mobility', 'rest'] as const;
const WORKOUT_STATUSES = ['done', 'skipped', 'modified'] as const;
const WORKOUT_VARIANTS = ['full', 'bare_min'] as const;
const CHECK_IN_TYPES = ['daily', 'weekly'] as const;
const DIFFICULTIES = ['Beginner', 'Intermediate', 'Advanced'] as const;

// One logged exercise entry. Everything but the name is optional — a quick log
// ("did squats") is still worth more than nothing, and bodyweight work has no
// weight to give.
const EXERCISE_SCHEMA = z.object({
	name: z.string().describe('e.g. "Back Squat"'),
	sets: z.number().int().min(1).optional(),
	reps: z.number().int().min(1).optional().describe('reps per set'),
	weight_lb: z.number().optional().describe('load in pounds; omit for bodyweight'),
	rpe: z.number().int().min(1).max(10).optional(),
	notes: z.string().optional()
});

const text = (value: unknown) => ({
	content: [{ type: 'text' as const, text: JSON.stringify(value, null, 2) }]
});

const errorText = (message: string) => ({
	content: [{ type: 'text' as const, text: message }],
	isError: true
});

export class CommandCenterMCP extends McpAgent<Env, Record<string, never>, Props> {
	server = new McpServer({ name: 'johnverrone-command-center', version: '2.0.0' });

	private get client() {
		return new CommandCenterClient({
			baseUrl: this.env.COACH_SITE_BASE_URL,
			token: this.env.COACH_API_TOKEN
		});
	}

	async init() {
		// --- Coach ---

		this.server.registerTool(
			'coach_get_today',
			{
				description:
					"Today's planned session, logged workouts (each with its exercises), habit toggles, streaks, latest coach check-in, and this week's adherence.",
				inputSchema: { date: z.string().optional().describe('yyyy-mm-dd, defaults to today') }
			},
			async ({ date }) => this.run(() => this.client.getToday(date))
		);

		this.server.registerTool(
			'coach_get_summary',
			{
				description:
					'Rolling summary for a weekly review: adherence, streaks, training volume by modality, recent logs (each with its exercises), latest body metrics, recent check-ins.',
				inputSchema: { days: z.number().int().min(1).max(90).optional().describe('default 7') }
			},
			async ({ days }) => this.run(() => this.client.getSummary(days))
		);

		this.server.registerTool(
			'coach_get_plan',
			{ description: 'The full weekly fitness plan template (all seven days).', inputSchema: {} },
			async () => this.run(() => this.client.getPlan())
		);

		this.server.registerTool(
			'coach_update_plan_session',
			{
				description:
					'Create, patch, or delete a session in the weekly fitness plan template. Omit id to create; pass id to patch; pass id + delete:true to remove.',
				inputSchema: {
					id: z.number().int().optional(),
					delete: z.boolean().optional(),
					name: z.string().optional(),
					modality: z.enum(MODALITIES).optional(),
					day_of_week: z.number().int().min(0).max(6).optional().describe('0=Sunday..6=Saturday'),
					sort_order: z.number().int().optional(),
					duration_min: z.number().int().nullable().optional(),
					prescription: z.string().nullable().optional(),
					bare_min: z.string().nullable().optional(),
					bare_min_duration_min: z.number().int().nullable().optional(),
					active: z.boolean().optional()
				}
			},
			async (input) => this.run(() => this.client.updatePlanSession(input))
		);

		this.server.registerTool(
			'coach_log_workout',
			{
				description:
					'Log a completed, skipped, or modified workout, optionally with per-exercise detail. Omit id to create; pass the id of an existing log (from coach_get_today) to patch it — the usual path for lifts, since a Whoop sync creates the workout row and the exercises get filled in afterward.',
				inputSchema: {
					id: z
						.number()
						.int()
						.optional()
						.describe('Existing workout log id to patch; omit to create a new log'),
					date: z.string().optional().describe('yyyy-mm-dd, defaults to today'),
					status: z.enum(WORKOUT_STATUSES).optional().describe('required when creating'),
					modality: z.enum(MODALITIES).optional().describe('required when creating'),
					plan_session_id: z.number().int().optional(),
					duration_min: z.number().int().optional(),
					rpe: z.number().int().min(1).max(10).optional(),
					notes: z.string().optional(),
					variant: z.enum(WORKOUT_VARIANTS).optional(),
					exercises: z
						.array(EXERCISE_SCHEMA)
						.optional()
						.describe(
							'Exercises performed, in order. One entry per exercise (or per distinct load — a back-off set can be its own entry with the same name).'
						),
					exercises_mode: z
						.enum(['replace', 'append'])
						.optional()
						.describe('How exercises apply to an existing log. Default replace.')
				}
			},
			async (input) => this.run(() => this.client.logWorkout(input))
		);

		this.server.registerTool(
			'coach_get_exercise_history',
			{
				description:
					'Progression for a single exercise by name: one entry per day with that day\'s top set (weight × reps × RPE) and estimated 1RM, newest first. Use this for "has my squat gone up?" instead of scanning workouts. Name matching ignores case, spaces, and hyphens.',
				inputSchema: {
					name: z.string().describe('Exercise name, e.g. "back squat"'),
					weeks: z
						.number()
						.int()
						.min(1)
						.max(52)
						.optional()
						.describe('Look back this many weeks; omit for all history'),
					limit: z.number().int().min(1).max(200).optional().describe('Max days returned, default 50')
				}
			},
			async (input) => this.run(() => this.client.getExerciseHistory(input))
		);

		this.server.registerTool(
			'coach_log_habit',
			{
				description:
					"Patch today's (or a given date's) habit toggles: no added sugar, no alcohol, mobility.",
				inputSchema: {
					date: z.string().optional().describe('yyyy-mm-dd, defaults to today'),
					no_added_sugar: z.boolean().optional(),
					no_alcohol: z.boolean().optional(),
					mobility_done: z.boolean().optional(),
					notes: z.string().optional()
				}
			},
			async (input) => this.run(() => this.client.logHabit(input))
		);

		this.server.registerTool(
			'coach_post_checkin',
			{
				description:
					'Post a coach check-in message (markdown) — shows up on the Today page. Use for daily nudges or the weekly review.',
				inputSchema: {
					type: z.enum(CHECK_IN_TYPES),
					content: z.string(),
					date: z.string().optional().describe('yyyy-mm-dd, defaults to today')
				}
			},
			async (input) => this.run(() => this.client.postCheckin(input))
		);

		// --- Guitar ---

		this.server.registerTool(
			'guitar_get_journal',
			{
				description:
					'The practice journal. Omit date for the full list (newest first); pass date for a single entry.',
				inputSchema: { date: z.string().optional().describe('yyyy-mm-dd') }
			},
			async ({ date }) => this.run(() => this.client.getGuitarJournal(date))
		);

		this.server.registerTool(
			'guitar_log_journal_entry',
			{
				description:
					'Create, patch, or delete a practice journal entry. Omit id to create (date must be unique); pass id to patch; pass id + delete:true to remove.',
				inputSchema: {
					id: z.number().int().optional(),
					delete: z.boolean().optional(),
					date: z.string().optional().describe('yyyy-mm-dd'),
					duration_min: z.number().int().optional(),
					theme: z.string().optional(),
					content: z.string().optional().describe('markdown practice notes')
				}
			},
			async (input) => this.run(() => this.client.updateGuitarJournalEntry(input))
		);

		this.server.registerTool(
			'guitar_get_plan',
			{ description: 'The current guitar practice plan (markdown).', inputSchema: {} },
			async () => this.run(() => this.client.getGuitarPlan())
		);

		this.server.registerTool(
			'guitar_update_plan',
			{
				description: 'Replace the guitar practice plan content wholesale.',
				inputSchema: { content: z.string() }
			},
			async ({ content }) => this.run(() => this.client.updateGuitarPlan(content))
		);

		this.server.registerTool(
			'guitar_list_songs',
			{ description: 'The song list (repertoire), ordered by sort order then title.', inputSchema: {} },
			async () => this.run(() => this.client.listGuitarSongs())
		);

		this.server.registerTool(
			'guitar_update_song',
			{
				description:
					'Create, patch, or delete a song. Omit id to create; pass id to patch; pass id + delete:true to remove.',
				inputSchema: {
					id: z.number().int().optional(),
					delete: z.boolean().optional(),
					title: z.string().optional(),
					artist: z.string().optional(),
					difficulty: z.enum(DIFFICULTIES).optional(),
					genre: z.string().optional(),
					key: z.string().optional(),
					tuning: z.string().optional(),
					bpm: z.number().int().optional(),
					capo: z.number().int().nullable().optional(),
					progress: z.string().optional(),
					tab_link: z.string().nullable().optional(),
					notes: z.string().nullable().optional(),
					sort_order: z.number().int().optional()
				}
			},
			async (input) => this.run(() => this.client.updateGuitarSong(input))
		);

		// --- Coffee ---

		this.server.registerTool(
			'coffee_create_bean',
			{
				description:
					'Add a coffee bean to johnverrone.com/coffee — typically from a photo of the bag. Reuses the roaster if it already exists (matched by name), otherwise creates it. New beans start as drafts; rating, flavors, and publishing happen later in the admin.',
				inputSchema: {
					name: z.string().describe('Bean name as printed on the bag, e.g. "Geometry"'),
					roaster: z.string().describe('Roaster name, e.g. "Onyx Coffee Lab"'),
					origins: z
						.array(z.string())
						.optional()
						.describe('Origin countries/regions, e.g. ["Ethiopia", "Colombia"]'),
					process: z
						.string()
						.optional()
						.describe('Processing method, e.g. "Washed", "Natural", "Honey"')
				}
			},
			async (input) => this.run(() => this.client.createCoffeeBean(input))
		);
	}

	/** Run an API call, turning failures into MCP tool errors instead of throwing. */
	private async run(fn: () => Promise<unknown>) {
		try {
			return text(await fn());
		} catch (e) {
			return errorText(e instanceof CommandCenterApiError ? e.message : `Unexpected error: ${e}`);
		}
	}
}

// OAuthProvider is a real, spec-compliant OAuth 2.1 authorization server: it
// owns /authorize, /token, /register, and the well-known discovery documents,
// so MCP clients that probe those endpoints (Claude Desktop, mcp-remote, etc.)
// get correct responses instead of the plain-text 404s that broke them before.
// Unauthenticated requests to /mcp are routed to GitHubHandler's consent +
// GitHub login flow (github-handler.ts), gated to a single allowed username.
export default new OAuthProvider({
	apiHandler: CommandCenterMCP.serve('/mcp') as any,
	apiRoute: '/mcp',
	authorizeEndpoint: '/authorize',
	clientRegistrationEndpoint: '/register',
	defaultHandler: GitHubHandler as any,
	tokenEndpoint: '/token'
});
