name: ci
on: [push]
jobs:
  build-and-containerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Login to gcloud registry
        id: gcloud
        uses: elgohr/gcloud-login-action@master
        with:
          account_key: ${{ secrets.GCLOUD_KEY }}

      - name: Publish to Registry
        if: startsWith(github.ref, 'refs/tags/')
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: verrone-gcp/tiger
          username: ${{ steps.gcloud.outputs.username }}
          password: ${{ steps.gcloud.outputs.password }}
          registry: gcr.io
          dockerfile: etc/docker/Dockerfile

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}